### ISSUE TITLE
'discord.h'?

### ISSUE THREAD

**Issue by Spasman** [GameMakerDiscord/Discord.gml#1]
I extracted the SDK into the correct folder for compiling but the Discord.gml solution seems to be looking for a "discord.h" header, which doesn't appear to be there. I'm using VS 2017.

Skipping that, importing the extension itself into GMS2 is also looking for a "Discord.gml.dll" file, but I'm assuming I get that from compiling successfully yeah? Thanks man.

**Comment by YellowAfterlife** [comment]
You might have mispositioned something - I just downloaded the latest SDK from their official channel and the "cpp" folder has a discord.h as expected

**Comment by Spasman** [comment]
I got it, I added "discord_game_sdk\cpp\" to the discord.h include line, and I had to manually include the .lib files for the sdk into the project (in the Solutions explorer tree)

Definitely me not understanding how cpp works,, but it compiled. Thanks a lot man!
